---
title: "Landus-Phyto"
author: "Jeremy Froidevaux"
date: "2023-11-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Load libraries
```{r}
library <- c("terra","ggplot2","grid","gridExtra","cowplot","landscapemetrics","data.table","maps",
             "ggsn","dplyr","rworldmap","reshape2","sf","terra","tidyverse","purrr") 
lapply(library, require, character.only = TRUE) 
```


## Data manipulation with raster and shape files
### Open CameraTrap csv file (and landus csv file if needed)
```{r}
camtrap<-fread("/Users/jeremyfroidevaux/Documents/Herbiland/CameraTrap/camerainfoBauges_20231127.csv")

```

### Transformation of latlong in vector and georeferenced data vizualization
```{r}
#All data

pts <- st_as_sf(camtrap,coords=c("long","lat"))
str(pts)
st_crs(pts) <- 2154
st_crs(pts)
st_write(pts, "/Users/jeremyfroidevaux/Documents/Herbiland/GIS/Bauges_camtrap/camtrap_locBauges", driver = "ESRI Shapefile")

```

### Plot rasters and camtrap loc
```{r}
dir.posPoints = "/Users/jeremyfroidevaux/Documents/Herbiland/GIS/Bauges_camtrap"  
name.points = "camtrap_locBauges"
loc<-st_read(dsn = dir.posPoints, layer = name.points)
dir.posEnvironmentalLayers = "/Users/jeremyfroidevaux/Documents/Herbiland/GIS/ORION/PRED/LC_pred_BAUGES_08062023.tif"

dir.dem = "/Users/jeremyfroidevaux/Documents/Herbiland/GIS/Topo/DEM_Alps/DEM_ALPS1.tif"
dem<-rast(dir.dem)
demproj<-project(dem, "EPSG:2154") #EPSG:2154 pour Lambert93
demproj
plot(demproj,axes = T,legend=FALSE)



orionrast<-rast(dir.posEnvironmentalLayers) 
orionrast
loc
plot(orionrast)
points(loc)

```